services:
  database:
    image: mysql:8.4.0
    container_name: wordpress-database
    restart: always
    volumes:
      - wp-database-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=wp
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - 3306:3306
    networks:
      - wordpress

  wordpress:
    image: wordpress:6.5.3-php8.3-fpm-alpine
    container_name: wordpress
    restart: always
    depends_on:
      - database
    environment:
      - WORDPRESS_DB_HOST=database:3306
      - WORDPRESS_DB_NAME=wp
      - WORDPRESS_DB_USER=mysql
      - WORDPRESS_DB_PASSWORD=mysql
    volumes:
      - wp-data:/var/www/html
    networks:
      - wordpress
    
  webserver:
    image: nginx:1.15.12-alpine
    container_name: wp-webserver
    depends_on:
      - wordpress
    restart: always
    volumes:
      - wp-data:/var/www/html
      - ./.nginx:/etc/nginx/conf.d
    ports:
      - 8080:80
    networks:
      - wordpress
    

volumes:
  wp-database-data:
  wp-data:

networks:
  wordpress:
    name: wordpress
    